import { describe, it, expect, beforeEach, afterEach, mock } from "bun:test"
import crypto from "node:crypto"
import * as sshpk from "sshpk"

import {
  VpnSshKeyAlreadyExistsError,
  VpnSshKeyInUseError,
  VpnSshKeyNotFoundError,
  VpnSshKeyService,
} from "./vpn-ssh-key.service"
import {
  computeSshKeyFingerprint,
  decryptSshPrivateKey,
  parseSshPrivateKey,
  resetVpnSshCrypto,
  VpnSshKeyError,
} from "./vpn-ssh-key.crypto"

type AnyFn = (...args: any[]) => any

const TEST_ENCRYPTION_KEY = "a".repeat(64)

const { privateKey: testPrivateKeyPem } = crypto.generateKeyPairSync(
  "ed25519",
  {
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
    publicKeyEncoding: { type: "spki", format: "pem" },
  }
)

const makeKey = (over: Record<string, unknown> = {}) => ({
  id: "key-1",
  name: "Prod Key",
  privateKey: "encrypted-blob",
  fingerprint: "SHA256:abc",
  createdAt: new Date("2026-01-01T00:00:00Z"),
  updatedAt: new Date("2026-01-01T00:00:00Z"),
  servers: [],
  ...over,
})

const findMany = mock<AnyFn>(async () => [])
const findUnique = mock<AnyFn>(async () => null)
const findFirst = mock<AnyFn>(async () => null)
const create = mock<AnyFn>(async () => makeKey())
const del = mock<AnyFn>(async () => makeKey())

const prismaMock = {
  vpnSshKey: { findMany, findUnique, findFirst, create, delete: del },
} as any

const service = new VpnSshKeyService(prismaMock)

beforeEach(() => {
  process.env.ENCRYPTION_KEY = TEST_ENCRYPTION_KEY
  resetVpnSshCrypto()
  findMany.mockClear()
  findUnique.mockClear()
  findFirst.mockClear()
  create.mockClear()
  del.mockClear()
  findUnique.mockResolvedValue(null)
  findFirst.mockResolvedValue(null)
  create.mockResolvedValue(makeKey())
  del.mockResolvedValue(makeKey())
})

afterEach(() => {
  resetVpnSshCrypto()
})

describe("computeSshKeyFingerprint", () => {
  it("produces a stable SHA256 fingerprint", () => {
    const fp1 = computeSshKeyFingerprint(testPrivateKeyPem as string)
    const fp2 = computeSshKeyFingerprint(testPrivateKeyPem as string)
    expect(fp1).toBe(fp2)
    expect(fp1).toMatch(/^SHA256:/)
  })

  it("throws on invalid key material", () => {
    expect(() => computeSshKeyFingerprint("not a key")).toThrow(VpnSshKeyError)
  })

  it("parses OpenSSH Ed25519 key generated by sshpk", () => {
    const opensshKey = sshpk.generatePrivateKey("ed25519").toString("openssh")
    const fp1 = computeSshKeyFingerprint(opensshKey)
    const fp2 = computeSshKeyFingerprint(opensshKey)
    expect(fp1).toMatch(/^SHA256:/)
    expect(fp1).toBe(fp2)
  })

  it("parses RSA PEM key", () => {
    const { privateKey: rsaPem } = crypto.generateKeyPairSync("rsa", {
      modulusLength: 2048,
      privateKeyEncoding: { type: "pkcs1", format: "pem" },
      publicKeyEncoding: { type: "spki", format: "pem" },
    })
    const fp = computeSshKeyFingerprint(rsaPem)
    expect(fp).toMatch(/^SHA256:/)
  })

  it("rejects encrypted OpenSSH key", () => {
    const encryptedKey = sshpk
      .generatePrivateKey("ed25519")
      .toString("openssh", { passphrase: "secret" })
    expect(() => computeSshKeyFingerprint(encryptedKey)).toThrow(
      "Encrypted SSH private keys are not supported"
    )
  })

  it("rejects public key string", () => {
    expect(() =>
      computeSshKeyFingerprint("ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILf4TEST")
    ).toThrow(VpnSshKeyError)
  })
})

describe("parseSshPrivateKey", () => {
  it("returns publicKeyDer and algorithm for OpenSSH Ed25519", () => {
    const opensshKey = sshpk.generatePrivateKey("ed25519").toString("openssh")
    const result = parseSshPrivateKey(opensshKey)
    expect(result.publicKeyDer).toBeInstanceOf(Buffer)
    expect(result.publicKeyDer.length).toBeGreaterThan(0)
    expect(result.algorithm).toBe("ed25519")
  })

  it("returns algorithm for RSA key", () => {
    const { privateKey: rsaPem } = crypto.generateKeyPairSync("rsa", {
      modulusLength: 2048,
      privateKeyEncoding: { type: "pkcs1", format: "pem" },
      publicKeyEncoding: { type: "spki", format: "pem" },
    })
    const result = parseSshPrivateKey(rsaPem)
    expect(result.algorithm).toBe("rsa")
  })

  it("rejects encrypted key with clear message", () => {
    const encryptedKey = sshpk
      .generatePrivateKey("ed25519")
      .toString("openssh", { passphrase: "secret" })
    expect(() => parseSshPrivateKey(encryptedKey)).toThrow(
      "Encrypted SSH private keys are not supported"
    )
  })

  it("rejects complete garbage", () => {
    expect(() => parseSshPrivateKey("not a key at all")).toThrow(VpnSshKeyError)
  })
})

describe("ssh private key encryption", () => {
  it("round-trips encrypt/decrypt and never stores plaintext", async () => {
    create.mockImplementation(async (args: any) => makeKey(args.data))
    const key = await service.create({
      name: "Prod Key",
      privateKey: testPrivateKeyPem as string,
    })
    expect(key.privateKey).not.toContain("PRIVATE KEY")
    expect(decryptSshPrivateKey(key.privateKey)).toBe(testPrivateKeyPem)
  })
})

describe("VpnSshKeyService.create", () => {
  it("computes fingerprint and persists encrypted key", async () => {
    await service.create({
      name: "Prod Key",
      privateKey: testPrivateKeyPem as string,
    })
    const data = create.mock.calls[0][0].data
    expect(data.fingerprint).toMatch(/^SHA256:/)
    expect(data.privateKey).not.toContain("PRIVATE KEY")
  })

  it("rejects duplicate key with the same fingerprint", async () => {
    const key1 = makeKey({ id: "key-1", name: "Prod Key" })
    findFirst.mockResolvedValue(key1)

    await expect(
      service.create({
        name: "Duplicate Key",
        privateKey: testPrivateKeyPem as string,
      })
    ).rejects.toBeInstanceOf(VpnSshKeyAlreadyExistsError)

    expect(create).not.toHaveBeenCalled()
  })
})

describe("VpnSshKeyService.remove", () => {
  it("deletes an unused key", async () => {
    findUnique.mockResolvedValue(makeKey({ servers: [] }))
    await service.remove("key-1")
    expect(del).toHaveBeenCalledTimes(1)
  })

  it("refuses to delete a key referenced by a server", async () => {
    findUnique.mockResolvedValue(makeKey({ servers: [{ name: "ID-01" }] }))
    await expect(service.remove("key-1")).rejects.toBeInstanceOf(
      VpnSshKeyInUseError
    )
    expect(del).not.toHaveBeenCalled()
  })

  it("throws when key missing", async () => {
    findUnique.mockResolvedValue(null)
    await expect(service.remove("missing")).rejects.toBeInstanceOf(
      VpnSshKeyNotFoundError
    )
  })
})
