codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "70...90"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: success
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true