export const PAYMENT_CONSTANTS = {
  MIN_TOPUP_AMOUNT: 10000,
  MAX_TOPUP_AMOUNT: 100000000, // 100 million
  DEFAULT_EXPIRY_DAYS: 7,
  MAX_EXPIRY_DAYS: 30,
  MIN_EXPIRY_DAYS: 1,
} as const

export const BANK_CODES = {
  BCA: { code: "BCA", name: "Bank Central Asia" },
  MANDIRI: { code: "MANDIRI", name: "Bank Mandiri" },
  BRI: { code: "BRI", name: "Bank Rakyat Indonesia" },
  BNI: { code: "BNI", name: "Bank Negara Indonesia" },
} as const

export const DUITKU_PAYMENT_METHODS = {
  VIRTUAL_ACCOUNT: "VC",
  QRIS: "QR",
} as const

export const PAYMENT_AUDIT_ACTIONS = {
  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  PAYMENT_APPROVED: "PAYMENT_APPROVED",
  PAYMENT_REJECTED: "PAYMENT_REJECTED",
  GATEWAY_CREATED: "GATEWAY_CREATED",
  GATEWAY_UPDATED: "GATEWAY_UPDATED",
  GATEWAY_TOGGLED: "GATEWAY_TOGGLED",
  BANK_ACCOUNT_CREATED: "BANK_ACCOUNT_CREATED",
  BANK_ACCOUNT_UPDATED: "BANK_ACCOUNT_UPDATED",
  BANK_ACCOUNT_TOGGLED: "BANK_ACCOUNT_TOGGLED",
  SETTINGS_UPDATED: "SETTINGS_UPDATED",
  DUITKU_CALLBACK_RECEIVED: "DUITKU_CALLBACK_RECEIVED",
  DUITKU_PAYMENT_COMPLETED: "DUITKU_PAYMENT_COMPLETED",
} as const
