"use client"

export {
  Archive as ArchiveBox,
  Archive as ArchiveBoxIcon,
  ArrowBendDownLeft,
  ArrowBendUpRight,
  ArrowClockwise,
  ArrowDown as ArrowDownIcon,
  ArrowLeft,
  ArrowLeftIcon,
  ArrowRight,
  ArrowRightIcon,
  ArrowUp as ArrowUpIcon,
  ArrowsClockwise,
  ArrowsDownUpIcon,
  ArrowsLeftRight,
  ArrowsOutSimple,
  Bank,
  BellIcon,
  BookOpen,
  BookOpenIcon,
  BuildingsIcon,
  Calendar,
  CaretDown,
  CaretDownIcon,
  CaretLeft,
  CaretLeftIcon,
  CaretRight,
  CaretRightIcon,
  CaretUpDownIcon,
  CaretUpIcon,
  ChartLine,
  ChartLineUp,
  ChatCircle,
  Check,
  CheckCircle,
  CheckCircleIcon,
  CheckIcon,
  Clock,
  ClockIcon,
  ClockCounterClockwise,
  Cloud,
  Code,
  Copy,
  Cpu,
  CreditCardIcon,
  Database,
  DiscordLogo,
  DotsThreeIcon,
  DotsThreeVertical,
  DotsThreeVerticalIcon,
  DownloadIcon,
  Envelope,
  ExportIcon,
  Eye,
  Eye as EyeIcon,
  EyeSlash,
  FileCode,
  Folder,
  GaugeIcon,
  Gear,
  Gear as GearIcon,
  GearSixIcon,
  GitBranch,
  GithubLogo,
  Globe,
  GlobeIcon,
  HandCoinsIcon,
  HardDrive,
  InfoIcon,
  Key,
  LifebuoyIcon,
  Lightning,
  List,
  Lock,
  MagnifyingGlass,
  MagnifyingGlassIcon,
  MagnifyingGlassMinus,
  MagnifyingGlassPlus,
  MegaphoneSimple as MegaphoneSimpleIcon,
  MonitorIcon,
  MoonIcon,
  Package,
  Package as PackageIcon,
  PaperPlane,
  PaperPlaneTilt,
  PaperPlaneTiltIcon,
  Pen,
  PencilSimple,
  PencilSimple as PencilSimpleIcon,
  Phone,
  Play,
  Plus,
  PlusIcon,
  Pulse,
  QrCodeIcon,
  Question,
  Quotes,
  ReceiptIcon,
  Robot,
  RocketLaunchIcon,
  RowsIcon,
  ShieldCheck as ShieldCheckIcon,
  ShieldWarning,
  SidebarIcon,
  SignOutIcon,
  SpinnerIcon,
  SquaresFour,
  SquaresFour as SquaresFourIcon,
  Star,
  SunIcon,
  Terminal,
  TerminalIcon,
  Timer,
  Triangle,
  Triangle as TriangleIcon,
  Trash,
  Trash as TrashIcon,
  TwitterLogo,
  UploadIcon,
  User,
  UserPlus,
  WalletIcon,
  Warning,
  WarningCircle,
  WarningCircle as WarningCircleIcon,
  WarningIcon,
  WhatsappLogoIcon,
  Wrench,
  X,
  XCircle,
  XCircleIcon,
  XIcon,
} from "@phosphor-icons/react"
