// This file is auto-generated by scripts/generate-template-icons.ts
// Do not edit manually. Run `bun run generate:template-icons` or `bun run build`.

export interface TemplateLocalIcon {
  slug: string
  name: string
  fileName: string
  path: string
}

export const TEMPLATE_LOCAL_ICONS: readonly TemplateLocalIcon[] = [
  {
    "slug": "9router",
    "name": "9router",
    "fileName": "9router.svg",
    "path": "/app-hosting/icons/9router.svg"
  },
  {
    "slug": "bun",
    "name": "Bun",
    "fileName": "bun.svg",
    "path": "/app-hosting/icons/bun.svg"
  },
  {
    "slug": "go",
    "name": "Go",
    "fileName": "go.svg",
    "path": "/app-hosting/icons/go.svg"
  },
  {
    "slug": "hermes",
    "name": "Hermes Agent",
    "fileName": "hermes.svg",
    "path": "/app-hosting/icons/hermes.svg"
  },
  {
    "slug": "laravel",
    "name": "Laravel",
    "fileName": "laravel.svg",
    "path": "/app-hosting/icons/laravel.svg"
  },
  {
    "slug": "n8n",
    "name": "n8n Automation",
    "fileName": "n8n.svg",
    "path": "/app-hosting/icons/n8n.svg"
  },
  {
    "slug": "nextjs",
    "name": "Next.js",
    "fileName": "nextjs.svg",
    "path": "/app-hosting/icons/nextjs.svg"
  },
  {
    "slug": "nodejs",
    "name": "Node.js",
    "fileName": "nodejs.svg",
    "path": "/app-hosting/icons/nodejs.svg"
  },
  {
    "slug": "omniroute",
    "name": "OmniRoute",
    "fileName": "omniroute.svg",
    "path": "/app-hosting/icons/omniroute.svg"
  },
  {
    "slug": "openclaw",
    "name": "OpenClaw",
    "fileName": "openclaw.svg",
    "path": "/app-hosting/icons/openclaw.svg"
  },
  {
    "slug": "php",
    "name": "PHP",
    "fileName": "php.svg",
    "path": "/app-hosting/icons/php.svg"
  },
  {
    "slug": "python",
    "name": "Python",
    "fileName": "python.svg",
    "path": "/app-hosting/icons/python.svg"
  },
  {
    "slug": "rust",
    "name": "Rust",
    "fileName": "rust.svg",
    "path": "/app-hosting/icons/rust.svg"
  },
  {
    "slug": "uptime-kuma",
    "name": "Uptime Kuma",
    "fileName": "uptime-kuma.svg",
    "path": "/app-hosting/icons/uptime-kuma.svg"
  },
  {
    "slug": "uv",
    "name": "uv",
    "fileName": "uv.svg",
    "path": "/app-hosting/icons/uv.svg"
  },
  {
    "slug": "vaultwarden",
    "name": "Vaultwarden",
    "fileName": "vaultwarden.svg",
    "path": "/app-hosting/icons/vaultwarden.svg"
  },
  {
    "slug": "wordpress",
    "name": "WordPress",
    "fileName": "wordpress.svg",
    "path": "/app-hosting/icons/wordpress.svg"
  }
] as const

export function getTemplateLocalIconByPath(
  path?: string | null
): TemplateLocalIcon | undefined {
  if (!path) return undefined
  return TEMPLATE_LOCAL_ICONS.find((icon) => icon.path === path)
}

export function getTemplateLocalIconBySlug(
  slug?: string | null
): TemplateLocalIcon | undefined {
  if (!slug) return undefined
  const normalized = slug.toLowerCase().trim()
  return TEMPLATE_LOCAL_ICONS.find((icon) => icon.slug === normalized)
}
