// This file is auto-generated by scripts/generate-template-icons.ts
// Do not edit manually. Run `bun run generate:template-icons` or `bun run build`.

export interface TemplateLocalIcon {
  slug: string
  name: string
  fileName: string
  path: string
}

export const TEMPLATE_LOCAL_ICONS: readonly TemplateLocalIcon[] = [
  {
    "slug": "9router",
    "name": "9router",
    "fileName": "9router.svg",
    "path": "/app-hosting/icons/9router.svg"
  },
  {
    "slug": "hermes",
    "name": "Hermes Agent",
    "fileName": "hermes.svg",
    "path": "/app-hosting/icons/hermes.svg"
  },
  {
    "slug": "n8n",
    "name": "n8n Automation",
    "fileName": "n8n.svg",
    "path": "/app-hosting/icons/n8n.svg"
  },
  {
    "slug": "openclaw",
    "name": "OpenClaw",
    "fileName": "openclaw.svg",
    "path": "/app-hosting/icons/openclaw.svg"
  }
] as const

export function getTemplateLocalIconByPath(
  path?: string | null
): TemplateLocalIcon | undefined {
  if (!path) return undefined
  return TEMPLATE_LOCAL_ICONS.find((icon) => icon.path === path)
}

export function getTemplateLocalIconBySlug(
  slug?: string | null
): TemplateLocalIcon | undefined {
  if (!slug) return undefined
  const normalized = slug.toLowerCase().trim()
  return TEMPLATE_LOCAL_ICONS.find((icon) => icon.slug === normalized)
}
