// This file is auto-generated by scripts/generate-template-icons.ts
// Do not edit manually. Run `bun run generate:template-icons` or `bun run build`.

export interface TemplateLocalIcon {
  slug: string
  name: string
  fileName: string
  path: string
}

export const TEMPLATE_LOCAL_ICONS: readonly TemplateLocalIcon[] = [
  {
    "slug": "9router",
    "name": "9router",
    "fileName": "9router.svg",
    "path": "/app-hosting/icons/9router.svg"
  },
  {
    "slug": "actix",
    "name": "Actix Web",
    "fileName": "actix.svg",
    "path": "/app-hosting/icons/actix.svg"
  },
  {
    "slug": "adonisjs",
    "name": "AdonisJS",
    "fileName": "adonisjs.svg",
    "path": "/app-hosting/icons/adonisjs.svg"
  },
  {
    "slug": "angular",
    "name": "Angular",
    "fileName": "angular.svg",
    "path": "/app-hosting/icons/angular.svg"
  },
  {
    "slug": "astro",
    "name": "Astro",
    "fileName": "astro.svg",
    "path": "/app-hosting/icons/astro.svg"
  },
  {
    "slug": "axum",
    "name": "Axum",
    "fileName": "axum.svg",
    "path": "/app-hosting/icons/axum.svg"
  },
  {
    "slug": "bun",
    "name": "Bun",
    "fileName": "bun.svg",
    "path": "/app-hosting/icons/bun.svg"
  },
  {
    "slug": "codeigniter",
    "name": "CodeIgniter",
    "fileName": "codeigniter.svg",
    "path": "/app-hosting/icons/codeigniter.svg"
  },
  {
    "slug": "directus",
    "name": "Directus",
    "fileName": "directus.svg",
    "path": "/app-hosting/icons/directus.svg"
  },
  {
    "slug": "django",
    "name": "Django",
    "fileName": "django.svg",
    "path": "/app-hosting/icons/django.svg"
  },
  {
    "slug": "elysia",
    "name": "Elysia",
    "fileName": "elysia.svg",
    "path": "/app-hosting/icons/elysia.svg"
  },
  {
    "slug": "express",
    "name": "Express.js",
    "fileName": "express.svg",
    "path": "/app-hosting/icons/express.svg"
  },
  {
    "slug": "fastapi",
    "name": "FastAPI",
    "fileName": "fastapi.svg",
    "path": "/app-hosting/icons/fastapi.svg"
  },
  {
    "slug": "fastify",
    "name": "Fastify",
    "fileName": "fastify.svg",
    "path": "/app-hosting/icons/fastify.svg"
  },
  {
    "slug": "fiber",
    "name": "Fiber",
    "fileName": "fiber.svg",
    "path": "/app-hosting/icons/fiber.svg"
  },
  {
    "slug": "filament",
    "name": "Filament",
    "fileName": "filament.svg",
    "path": "/app-hosting/icons/filament.svg"
  },
  {
    "slug": "flask",
    "name": "Flask",
    "fileName": "flask.svg",
    "path": "/app-hosting/icons/flask.svg"
  },
  {
    "slug": "gin",
    "name": "Gin",
    "fileName": "gin.svg",
    "path": "/app-hosting/icons/gin.svg"
  },
  {
    "slug": "go",
    "name": "Go",
    "fileName": "go.svg",
    "path": "/app-hosting/icons/go.svg"
  },
  {
    "slug": "gradio",
    "name": "Gradio",
    "fileName": "gradio.svg",
    "path": "/app-hosting/icons/gradio.svg"
  },
  {
    "slug": "hermes",
    "name": "Hermes Agent",
    "fileName": "hermes.svg",
    "path": "/app-hosting/icons/hermes.svg"
  },
  {
    "slug": "hono",
    "name": "Hono",
    "fileName": "hono.svg",
    "path": "/app-hosting/icons/hono.svg"
  },
  {
    "slug": "laravel",
    "name": "Laravel",
    "fileName": "laravel.svg",
    "path": "/app-hosting/icons/laravel.svg"
  },
  {
    "slug": "n8n",
    "name": "n8n Automation",
    "fileName": "n8n.svg",
    "path": "/app-hosting/icons/n8n.svg"
  },
  {
    "slug": "nestjs",
    "name": "NestJS",
    "fileName": "nestjs.svg",
    "path": "/app-hosting/icons/nestjs.svg"
  },
  {
    "slug": "nextjs",
    "name": "Next.js",
    "fileName": "nextjs.svg",
    "path": "/app-hosting/icons/nextjs.svg"
  },
  {
    "slug": "nodejs",
    "name": "Node.js",
    "fileName": "nodejs.svg",
    "path": "/app-hosting/icons/nodejs.svg"
  },
  {
    "slug": "nuxt",
    "name": "Nuxt",
    "fileName": "nuxt.svg",
    "path": "/app-hosting/icons/nuxt.svg"
  },
  {
    "slug": "omniroute",
    "name": "OmniRoute",
    "fileName": "omniroute.svg",
    "path": "/app-hosting/icons/omniroute.svg"
  },
  {
    "slug": "openclaw",
    "name": "OpenClaw",
    "fileName": "openclaw.svg",
    "path": "/app-hosting/icons/openclaw.svg"
  },
  {
    "slug": "php",
    "name": "PHP",
    "fileName": "php.svg",
    "path": "/app-hosting/icons/php.svg"
  },
  {
    "slug": "python",
    "name": "Python",
    "fileName": "python.svg",
    "path": "/app-hosting/icons/python.svg"
  },
  {
    "slug": "rails",
    "name": "Ruby on Rails",
    "fileName": "rails.svg",
    "path": "/app-hosting/icons/rails.svg"
  },
  {
    "slug": "react",
    "name": "React",
    "fileName": "react.svg",
    "path": "/app-hosting/icons/react.svg"
  },
  {
    "slug": "remix",
    "name": "Remix",
    "fileName": "remix.svg",
    "path": "/app-hosting/icons/remix.svg"
  },
  {
    "slug": "rust",
    "name": "Rust",
    "fileName": "rust.svg",
    "path": "/app-hosting/icons/rust.svg"
  },
  {
    "slug": "solidjs",
    "name": "SolidJS",
    "fileName": "solidjs.svg",
    "path": "/app-hosting/icons/solidjs.svg"
  },
  {
    "slug": "spring",
    "name": "Spring Boot",
    "fileName": "spring.svg",
    "path": "/app-hosting/icons/spring.svg"
  },
  {
    "slug": "strapi",
    "name": "Strapi",
    "fileName": "strapi.svg",
    "path": "/app-hosting/icons/strapi.svg"
  },
  {
    "slug": "streamlit",
    "name": "Streamlit",
    "fileName": "streamlit.svg",
    "path": "/app-hosting/icons/streamlit.svg"
  },
  {
    "slug": "svelte",
    "name": "Svelte",
    "fileName": "svelte.svg",
    "path": "/app-hosting/icons/svelte.svg"
  },
  {
    "slug": "symfony",
    "name": "Symfony",
    "fileName": "symfony.svg",
    "path": "/app-hosting/icons/symfony.svg"
  },
  {
    "slug": "uptime-kuma",
    "name": "Uptime Kuma",
    "fileName": "uptime-kuma.svg",
    "path": "/app-hosting/icons/uptime-kuma.svg"
  },
  {
    "slug": "uv",
    "name": "uv",
    "fileName": "uv.svg",
    "path": "/app-hosting/icons/uv.svg"
  },
  {
    "slug": "vaultwarden",
    "name": "Vaultwarden",
    "fileName": "vaultwarden.svg",
    "path": "/app-hosting/icons/vaultwarden.svg"
  },
  {
    "slug": "vite",
    "name": "Vite",
    "fileName": "vite.svg",
    "path": "/app-hosting/icons/vite.svg"
  },
  {
    "slug": "vue",
    "name": "Vue",
    "fileName": "vue.svg",
    "path": "/app-hosting/icons/vue.svg"
  },
  {
    "slug": "wordpress",
    "name": "WordPress",
    "fileName": "wordpress.svg",
    "path": "/app-hosting/icons/wordpress.svg"
  }
] as const

export function getTemplateLocalIconByPath(
  path?: string | null
): TemplateLocalIcon | undefined {
  if (!path) return undefined
  return TEMPLATE_LOCAL_ICONS.find((icon) => icon.path === path)
}

export function getTemplateLocalIconBySlug(
  slug?: string | null
): TemplateLocalIcon | undefined {
  if (!slug) return undefined
  const normalized = slug.toLowerCase().trim()
  return TEMPLATE_LOCAL_ICONS.find((icon) => icon.slug === normalized)
}
