import { readFileSync, writeFileSync } from "node:fs"

// ==========================================
// 1. Patch types.ts
// ==========================================
let types = readFileSync("lib/i18n/messages/types.ts", "utf8")

// 1a. deploy additions
const deployAdditions = `        vpaExplainOff: string
      }
      templateEditor: {
        official: string
        featured: string
        subtitle: string
        version: string
        copyId: string
        idPrefix: string
        importJson: string
        exportJson: string
        approve: string
        reject: string
        delete: string
        tabs: {
          generalDocs: string
          runtimeServices: string
          envSchema: string
          installations: string
        }
        identity: {
          title: string
          description: string
          displayName: string
          displayNamePlaceholder: string
          slug: string
          tagline: string
          taglinePlaceholder: string
          descriptionLabel: string
          descriptionPlaceholder: string
          iconUrl: string
          iconUrlPlaceholder: string
        }
        catalogPricing: {
          title: string
          description: string
          category: string
          categories: {
            ai: string
            automation: string
            cms: string
            database: string
            developerTools: string
            analytics: string
            utilities: string
          }
          visibility: string
          publicLive: string
          releaseVersion: string
          monthlyPrice: string
          officialBadgeTitle: string
          officialBadgeDescription: string
          featuredBadgeTitle: string
          featuredBadgeDescription: string
        }
        documentation: {
          title: string
          description: string
          writeTab: string
          previewTab: string
          placeholder: string
          empty: string
        }
        runtime: {
          title: string
          description: string
          dockerImage: string
          dockerImagePlaceholder: string
          defaultPort: string
          workloadType: string
          deployment: string
          statefulSet: string
          containerCommand: string
          containerCommandPlaceholder: string
          containerCommandHelp: string
          containerArgs: string
          containerArgsPlaceholder: string
          containerArgsHelp: string
          probesTitle: string
          probesDescription: string
          livenessPath: string
          livenessPathPlaceholder: string
          startupPath: string
          startupPathPlaceholder: string
          startupDelay: string
          startupThreshold: string
          readinessPath: string
          readinessPathPlaceholder: string
          readinessDelay: string
          probesHelp: string
          additionalPortsTitle: string
          additionalPortsDescription: string
          addPort: string
          portNamePlaceholder: string
          runAsNonRoot: string
          runAsNonRootDescription: string
        }
        resourcesStorage: {
          title: string
          description: string
          cpuLabel: string
          cpuHint: string
          cpuPlaceholder: string
          memoryLabel: string
          storageTitle: string
          storageDescription: string
          mountPath: string
          sizeGb: string
          singleNodeConstraintTitle: string
          singleNodeConstraintDescription: string
          volumeMountsTitle: string
          volumeMountsDescription: string
          readOnlyBadge: string
          addMountButton: string
          mountType: string
          mountTypes: {
            configMap: string
            secret: string
            pvc: string
            emptyDir: string
          }
          volumeName: string
          volumeNamePlaceholder: string
          mountPathLabel: string
          mountPathPlaceholder: string
          sourceName: string
          sourceNamePlaceholder: string
          readOnlySwitch: string
          submitMount: string
        }
        dependencies: {
          title: string
          description: string
          envPrefix: string
        }
        envSchema: {
          title: string
          description: string
          addVariable: string
          empty: string
          addFirst: string
          key: string
          keyPlaceholder: string
          label: string
          labelPlaceholder: string
          type: string
          types: {
            string: string
            number: string
            boolean: string
            select: string
          }
          defaultValue: string
          defaultValuePlaceholder: string
          descriptionLabel: string
          descriptionPlaceholder: string
          randomHex: string
          randomHexPlaceholder: string
          options: string
          optionsPlaceholder: string
          required: string
          requiredHint: string
          secret: string
          secretHint: string
          fixed: string
          fixedHint: string
          hidden: string
          hiddenHint: string
          previewTitle: string
          previewDescription: string
          hiddenBadge: string
          lockedBadge: string
          secretBadge: string
        }
        dialogs: {
          deleteTitle: string
          deleteDescriptionBefore: string
          deleteDescriptionAfter: string
          deleteCancel: string
          deleteConfirm: string
          rejectTitle: string
          rejectDescription: string
          rejectPlaceholder: string
          rejectCancel: string
          rejectConfirm: string
          importTitle: string
          importDescription: string
          uploadFile: string
          fileLoadedBefore: string
          fileLoadedAfter: string
          importPlaceholder: string
          importCancel: string
          importApply: string
        }
      }
      operateOverview: {
        repoDeployStatus: string
        repoDeployStatusDesc: string
        sourceProvider: string
        repository: string
        activeBranch: string
        lastSyncedCommit: string
        manualBuildPrompt: string
        rebuildButton: string
        rebuildingButton: string
        buildLogsTitle: string
        diagnosticsTitle: string
        diagnosticsDesc: string
        healthCheckTitle: string
        healthNormalDesc: string
        badGatewayTitle: string
        rootCause: string
        badGatewayCause: string
        badGatewaySolution: string
        sslFailTitle: string
        sslFailCause: string
        sslFailSolution: string
        redirectLoopTitle: string
        redirectLoopCause: string
        redirectLoopSolution: string
        endpointDetailsTitle: string
        clusterHost: string
        targetPort: string
        replicas: string
        active: string
      }
      operateTraffic: {
        canvasTitle: string
        loading: string
        canvasSubtitle: string
        activeDomain: string
        cloudflare: string
        database: string
        internet: string
        userTraffic: string
        cloudflareNode: string
        sslFullStrict: string
        sslHandshakeFail: string
        loopDetected: string
        sslActiveAcm: string
        k8sNamespace: string
        cpu: string
        ram: string
        status: string
        mysqlDb: string
        activeConns: string
        zoomIn: string
        zoomOut: string
        resetZoom: string
        legendHealthy: string
        legendBlocked: string
        legendProxied: string
      }
      operateMounts: {
        persistentVolumeTitle: string
        persistentVolumeDesc: string
        persistentVolumeRwo: string
        fileMountsTitle: string
        fileMountsDesc: string
        mountName: string
        mountNamePlaceholder: string
        targetPath: string
        targetPathPlaceholder: string
        targetPathHelp: string
        contentData: string
        readOnly: string
        readOnlyDesc: string
        setReadOnlyAria: string
        createButton: string
        activeMountsTitle: string
        activeMountsDesc: string
        colTarget: string
        colType: string
        colSummary: string
        colActions: string
        readOnlyDot: string
        readWriteDot: string
        deleteAria: string
        emptyState: string
        howItWorksTitle: string
        howItWorksDesc: string
      }
      gitDeploy: {
        review: {
          summaryTitle: string
          summaryDesc: string
          sourceRepo: string
          targetBranch: string
          frameworkRuntime: string
          buildCommand: string
          publicEndpoint: string
          allocatedResources: string
          vcpuSuffix: string
          ramSuffix: string
          envVars: string
          varsConfigured: string
          pricingPreflight: string
          pricingPreflightDesc: string
          hourlyRate: string
          billedPerSecond: string
          estMonthly: string
          projectedRuntime: string
          precheckStatus: string
          checkingBalance: string
          balanceVerified: string
          available: string
          lowBalance: string
          topUpRecommended: string
          notVerified: string
          verifiedUponDeploy: string
          editConfig: string
          initiatingDeploy: string
          deployApp: string
        }
        build: {
          changeRepo: string
          frameworkDetection: string
          confidence: string
          framework: string
          runtimeEngine: string
          packageManager: string
          settingsTitle: string
          settingsDesc: string
          buildCommand: string
          buildCommandPlaceholder: string
          outputDirectory: string
          outputDirectoryPlaceholder: string
          startCommand: string
          startCommandPlaceholder: string
          appPort: string
          customDockerfile: string
          customDockerfileDesc: string
          dockerfilePath: string
          envVars: string
          envVarsDesc: string
          envValuePlaceholder: string
          addVariable: string
          backToSource: string
          continueToSizing: string
        }
        source: {
          repoUrlTab: string
          connectedTab: string
          repoSourceTitle: string
          repoSourceDesc: string
          repoUrlLabel: string
          branchLabel: string
          rootDirLabel: string
          inspectingVisibility: string
          detectingPermissions: string
          checkingPublicOrApp: string
          publicAccess: string
          authorizedViaApp: string
          privateRepo: string
          inspectionFailed: string
          retryInspection: string
          connectedHeading: string
          connectedDesc: string
          configureRepos: string
          appNotConnected: string
          connectPrompt: string
          connectButton: string
          searchPlaceholder: string
          importButton: string
        }
      }`

types = types.replace(`        vpaExplainOff: string\n      }`, deployAdditions)

// 1b. deployWizard environment additions
const envAdditions = `          deploy: string
          attachedResources: string
          noDatabases: string
          settingsTitle: string
          settingsDesc: string`

types = types.replace(`          deploy: string`, envAdditions)

// 1c. adminBillingCatalog, adminBillingPayments, adminBillingPromotions under console
const catalogBillingTypes = `    adminBillingCatalog: {
      productDetail: {
        removePrice: string
        backToProducts: string
        catalog: string
        code: string
        duplicate: string
        deleteProduct: string
        deleteProductTierTitle: string
        planCode: string
        deleteDescBefore: string
        deleteDescAfter: string
        deleteNote: string
        deleteNoteDesc: string
        cancel: string
        productIdentity: string
        productIdentityDesc: string
        productCode: string
        productCodePlaceholder: string
        productName: string
        productNamePlaceholder: string
        activeInCatalog: string
        activeInCatalogDesc: string
        billingInventory: string
        billingInventoryDesc: string
        billingStrategy: string
        fixedCycle: string
        prorata: string
        inventoryTracking: string
        enforceStock: string
        availableStock: string
        allowBackorder: string
        formFieldsTitle: string
        formFieldsDesc: string
        deleteSelectedBefore: string
        deleteSelectedAfter: string
        addFormField: string
        noFormFields: string
        selectAllFieldsBefore: string
        selectAllFieldsAfter: string
        fieldLabel: string
        fieldLabelPlaceholder: string
        attributeKey: string
        attributeKeyPlaceholder: string
        inputType: string
        types: {
          text: string
          number: string
          email: string
          phone: string
          url: string
          dropdown: string
          radio: string
          checkbox: string
        }
        required: string
        deleteFieldAria: string
        optionsPlaceholder: string
        placeholderHint: string
        helperText: string
        helperTextPlaceholder: string
        helperTextOptional: string
        helperTextOptionalPlaceholder: string
        validationPattern: string
        validationPatternPlaceholder: string
        resourcesQuotas: string
        resourcesQuotasDesc: string
        addResource: string
        noResources: string
        selectAllResourcesBefore: string
        selectAllResourcesAfter: string
        keyAttribute: string
        keyAttributePlaceholder: string
        allocatedValue: string
        removeResource: string
        pricingTerms: string
        pricingTermsDesc: string
        defaultCurrency: string
        addTerm: string
        noPricingTerms: string
        missingCurrency: string
        filterTermsPlaceholder: string
        noTermsEmpty: string
        duplicateProduct: string
        duplicateDescBefore: string
        duplicateDescAfter: string
        newProductCode: string
        newProductCodePlaceholder: string
        mustBeUnique: string
        catalogSuffix: string
        newProductName: string
        newProductNamePlaceholder: string
      }
      productList: {
        backToCatalog: string
        title: string
        description: string
        newProduct: string
        noProducts: string
        noProductsDesc: string
        addFirstProduct: string
        code: string
        unlimitedStock: string
        startingFrom: string
        edit: string
        duplicate: string
        delete: string
        deleteProductPlan: string
        deleteConfirmDesc: string
        cancel: string
        archiveInsteadTitle: string
        archiveProductBefore: string
        archiveProductAfter: string
        archivePrompt: string
        archiveAction: string
        cannotBeUndone: string
        duplicateTitle: string
        duplicateDescBefore: string
        duplicateDescAfter: string
        newProductCode: string
        newProductCodePlaceholder: string
        mustBeUnique: string
        catalogSuffix: string
        newProductName: string
        newProductNamePlaceholder: string
      }
      addonDetail: {
        removePrice: string
        code: string
        archived: string
        archive: string
        archiveTitle: string
        archiveDesc: string
        cancel: string
        identity: string
        identityDesc: string
        codeLabel: string
        codePlaceholder: string
        name: string
        namePlaceholder: string
        billingMode: string
        description: string
        descriptionPlaceholder: string
        defaultCurrency: string
        active: string
        pricingTerms: string
        pricingTermsDesc: string
        addTerm: string
        noPricingTerms: string
        searchPricingTerms: string
        noPricingTermsEmpty: string
        allTermsValid: string
        pricingPreview: string
        pricingPreviewDesc: string
        searchPreview: string
        noActivePrices: string
      }
      catalogPlansTab: {
        code: string
        selectedFromVpn: string
        removePlan: string
        name: string
        namePlaceholder: string
        codeLabel: string
        codePlaceholder: string
        billingStrategy: string
        fixedCycle: string
        prorata: string
        inventoryStock: string
        trackStock: string
        availableCountPlaceholder: string
        allowBackorders: string
        pricingRequired: string
        enabledTerms: string
        enableTermsDesc: string
        currency: string
        requiredPlaceholder: string
        mustBePositive: string
        previewReadOnly: string
        noPlansConfigured: string
        addPlan: string
      }
    }
    adminBillingPayments: {
      confirmations: {
        colInvoice: string
        colSubmitted: string
        colAmount: string
        colBankAccount: string
        colStatus: string
        colNotes: string
        actions: string
        review: string
        retry: string
        title: string
        description: string
        searchPlaceholder: string
        emptyMessage: string
        reviewModalTitle: string
        reviewModalDesc: string
        labelInvoice: string
        labelInvoiceTotal: string
        labelSubmittedAmount: string
        labelStatus: string
        labelBank: string
        labelAccountNumber: string
        labelAccountHolder: string
        labelSubmitted: string
        overpaymentDetected: string
        customerTransferred: string
        overpaymentHelp: string
        labelNotes: string
        verifiedAmountPrefix: string
        verifiedAmountSuffix: string
        rejectionReason: string
        rejectionPlaceholder: string
        close: string
        rejectPayment: string
        approvePayment: string
      }
      bankAccounts: {
        colBank: string
        colAccount: string
        colCurrencies: string
        colStatus: string
        defaultBadge: string
        setAsDefault: string
        edit: string
        delete: string
        retry: string
        title: string
        addBankAccount: string
        bankName: string
        bankNamePlaceholder: string
        accountNumber: string
        accountHolder: string
        accountHolderPlaceholder: string
        supportedCurrencies: string
        swiftCode: string
        bankAddress: string
        bankAddressPlaceholder: string
        cancel: string
        noAccountsYet: string
        searchPlaceholder: string
        emptyMessage: string
      }
      currencies: {
        colCurrency: string
        colRate: string
        colTopUpRange: string
        colStatus: string
        baseBadge: string
        edit: string
        retry: string
        title: string
        descriptionPrefix: string
        descriptionSuffix: string
        addCurrency: string
        createSubmitLabel: string
        saveSubmitLabel: string
        searchPlaceholder: string
        emptyMessage: string
        codeIso: string
        name: string
        namePlaceholder: string
        symbol: string
        ratePerBase: string
        minTopUp: string
        maxTopUp: string
        baseCurrencyNotice: string
        cancel: string
      }
    }
    adminBillingPromotions: {
      list: {
        copyTitle: string
        actions: string
        actionsAria: string
        editDetails: string
        deactivate: string
        markExpired: string
        title: string
        description: string
        createVoucher: string
        filters: string
        searchPlaceholder: string
        statusPlaceholder: string
        typePlaceholder: string
        searchTablePlaceholder: string
        noVouchersMatch: string
        discount: string
        claims: string
        expires: string
        target: string
        page: string
        of: string
        totalSuffix: string
        previous: string
        next: string
      }
      voucherTypeTab: {
        title: string
        description: string
        kind: string
        kindAria: string
        kindImmutableNotice: string
        creditAmount: string
        creditAmountDesc: string
        currency: string
        currencyIdr: string
        currencyUsd: string
        discountType: string
        discountTypePlaceholder: string
        percentage: string
        fixedAmount: string
        discountValue: string
        discountCurrency: string
        sameAsVoucher: string
        currencyPolicy: string
        matchCurrency: string
        convertCheckout: string
        convertRedemption: string
        discountPolicyDesc: string
        firstCheckoutOnly: string
        firstCheckoutOnlyDesc: string
        allowUpgrades: string
        allowUpgradesDesc: string
        stackable: string
        stackableDesc: string
      }
    }`

types = types.replace(
  `    adminBillingOrders: {`,
  `${catalogBillingTypes}\n    adminBillingOrders: {`
)

// 1d. console.invoices pdf addition
const invoicePdfType = `      noInvoices: string
      pdf: {
        billTo: string
        paymentDetails: string
        bankTransferDesc: string
        bank: string
        acct: string
        name: string
        swift: string
        afterTransferNotice: string
        site: string
        support: string
        generatedOn: string
        at: string
        companyName: string
        companyAddress: string
        companyContact: string
        labelIssued: string
        labelDue: string
        labelServicePeriod: string
        labelServiceEnds: string
        labelNextRenewal: string
        labelPaymentMethod: string
        lineItems: string
        colDescription: string
        colQty: string
        colUnitPrice: string
        colAmount: string
        subtotal: string
        tax: string
        discount: string
        total: string
      }`

types = types.replace(`      noInvoices: string`, invoicePdfType)

writeFileSync("lib/i18n/messages/types.ts", types)
console.log("types.ts patched cleanly!")
