import fs from "node:fs"
import path from "node:path"

export interface TemplateLocalIcon {
  slug: string
  name: string
  fileName: string
  path: string
}

const SUPPORTED_EXTENSIONS = new Set([
  ".svg",
  ".png",
  ".webp",
  ".jpg",
  ".jpeg",
  ".gif",
  ".ico",
])

const KNOWN_LABELS: Record<string, string> = {
  "9router": "9router",
  actix: "Actix Web",
  adonisjs: "AdonisJS",
  angular: "Angular",
  astro: "Astro",
  axum: "Axum",
  bun: "Bun",
  codeigniter: "CodeIgniter",
  directus: "Directus",
  django: "Django",
  elysia: "Elysia",
  express: "Express.js",
  fastapi: "FastAPI",
  fastify: "Fastify",
  fiber: "Fiber",
  filament: "Filament",
  flask: "Flask",
  gin: "Gin",
  go: "Go",
  gradio: "Gradio",
  hermes: "Hermes Agent",
  hono: "Hono",
  laravel: "Laravel",
  n8n: "n8n Automation",
  nestjs: "NestJS",
  nextjs: "Next.js",
  nodejs: "Node.js",
  nuxt: "Nuxt",
  omniroute: "OmniRoute",
  openclaw: "OpenClaw",
  php: "PHP",
  python: "Python",
  rails: "Ruby on Rails",
  react: "React",
  remix: "Remix",
  rust: "Rust",
  solidjs: "SolidJS",
  spring: "Spring Boot",
  strapi: "Strapi",
  streamlit: "Streamlit",
  svelte: "Svelte",
  symfony: "Symfony",
  umami: "Umami Analytics",
  "uptime-kuma": "Uptime Kuma",
  uv: "uv",
  vaultwarden: "Vaultwarden",
  vite: "Vite",
  vue: "Vue",
  wordpress: "WordPress",
}

export function formatIconName(slug: string): string {
  const normalized = slug.toLowerCase().trim()
  if (KNOWN_LABELS[normalized]) {
    return KNOWN_LABELS[normalized]
  }
  return slug
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase())
    .trim()
}

export function scanTemplateLocalIcons(iconsDir: string): TemplateLocalIcon[] {
  if (!fs.existsSync(iconsDir)) {
    return []
  }

  const entries = fs.readdirSync(iconsDir, { withFileTypes: true })
  const icons: TemplateLocalIcon[] = []

  for (const entry of entries) {
    if (!entry.isFile()) continue
    const ext = path.extname(entry.name).toLowerCase()
    if (!SUPPORTED_EXTENSIONS.has(ext)) continue

    const slug = path.basename(entry.name, ext).toLowerCase().trim()
    const name = formatIconName(slug)
    const fileName = entry.name
    const webPath = `/app-hosting/icons/${fileName}`

    icons.push({
      slug,
      name,
      fileName,
      path: webPath,
    })
  }

  icons.sort((a, b) => a.slug.localeCompare(b.slug))
  return icons
}

export function generateTemplateIconsCode(icons: TemplateLocalIcon[]): string {
  const jsonIcons = JSON.stringify(icons, null, 2)

  return `// This file is auto-generated by scripts/generate-template-icons.ts
// Do not edit manually. Run \`bun run generate:template-icons\` or \`bun run build\`.

export interface TemplateLocalIcon {
  slug: string
  name: string
  fileName: string
  path: string
}

export const TEMPLATE_LOCAL_ICONS: readonly TemplateLocalIcon[] = ${jsonIcons} as const

export function getTemplateLocalIconByPath(
  path?: string | null
): TemplateLocalIcon | undefined {
  if (!path) return undefined
  return TEMPLATE_LOCAL_ICONS.find((icon) => icon.path === path)
}

export function getTemplateLocalIconBySlug(
  slug?: string | null
): TemplateLocalIcon | undefined {
  if (!slug) return undefined
  const normalized = slug.toLowerCase().trim()
  return TEMPLATE_LOCAL_ICONS.find((icon) => icon.slug === normalized)
}
`
}

export function generateTemplateIconsFile(
  iconsDir = path.join(process.cwd(), "public/app-hosting/icons"),
  outputFile = path.join(
    process.cwd(),
    "modules/deploy/constants/template-local-icons.generated.ts"
  )
): { count: number; icons: TemplateLocalIcon[] } {
  const icons = scanTemplateLocalIcons(iconsDir)
  const code = generateTemplateIconsCode(icons)

  const outputDir = path.dirname(outputFile)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  fs.writeFileSync(outputFile, code, "utf-8")
  return { count: icons.length, icons }
}

if (import.meta.main) {
  try {
    const result = generateTemplateIconsFile()
    console.log(
      `[generate-template-icons] Successfully generated ${result.count} local icons:`
    )
    for (const icon of result.icons) {
      console.log(`  - ${icon.slug} (${icon.name}): ${icon.path}`)
    }
  } catch (err) {
    console.error("[generate-template-icons] Error generating icons:", err)
    process.exit(1)
  }
}
